name: 'SolutionExport'
description: 'Exports a solution and opens a PR'
author: 'ekaradzha <ekaradzhaqb@quickbase.com>'

# Define your inputs here.
inputs:
  gh_token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
  gh_repo:
    description: 'GitHub repository'
    required: true
    default: '${{ github.repository }}'

  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  yaml:
    description: 'Solution yaml'

runs:
  using: node20
  main: dist/index.js
