name: 'Solution Export PR'
description:
  'Exports a Quickbase Solution and creates a PR in a GitHub repository'
author: 'ekaradzha@quickbase.com'

# Define your inputs here.
inputs:
  gh_token:
    description: 'GitHub token'
    required: true
  owner_name:
    description: 'Owner name of the repository'
    required: true
  owner_email:
    description: 'Owner email of the repository'
    required: true
  #Custom repo settings
  pr_title:
    description: 'Title of the PR'
    default: 'Export solution version'
  pr_description:
    description: 'Description for the auto-created PR'
    default: 'See the difference between the old and new solution QBL'
  branch_name:
    description: 'Branch name to create PR in'
    default: 'new-solution-version'
  # QBL settings
  qb_user_token:
    description: 'Quickbase user token'
    required: true
  qb_realm:
    description: 'Quickbase realm name'
    required: true
  qbl_version:
    description: 'Quickbase QBL version'
    default: '0.2'
  qbl_filename:
    description:
      'Filename for the QBL file the will be checked in the repository'
    default: 'solution.yaml'
  qb_solution_id:
    description: 'ID of solution that will be exported'
    required: true

# Define your outputs here.
outputs:
  head_branch:
    description: 'Name of the branch'

runs:
  using: node20
  main: dist/index.js
