name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  gh_token:
    description: 'GitHub token'
    required: true
  solution_id:
    description: 'ID of solution to export'
    required: true
  pr_title:
    description: 'Title of the PR'
    required: true
    default: 'Export solution version'
  repo:
    description: 'Repository to create PR in'
    required: true
  qb_tk:
    description: 'Quickbase user token'
    required: true
  qb_realm:
    description: 'Quickbase realm name'
    required: true
  branch_name:
    description: 'Branch name to create PR in'
    required: true
    default: 'new-solution-version'
  owner:
    description: 'Owner of the repository'
    required: true
  owner_name:
    description: 'Owner name of the repository'
    required: true
  owner_email:
    description: 'Owner email of the repository'
    required: true

# Define your outputs here.
outputs:
  yaml:
    description: 'Solution yaml'

runs:
  using: node20
  main: dist/index.js
